### Creates new request to rename the city
POST http://localhost:8080/cities/edit
Authorization: Basic MzkzODc6bjBVMnlzTTk=
Content-Type: application/json

{
  "countryCode": 23,
  "oldName": "from",
  "newName": "to",
  "reason": "reason"
}

### Deletes created cities request
DELETE http://localhost:8080/cities/edit/1
Authorization: Basic MzkzODc6bjBVMnlzTTk=

### Approves creates cities request. Requries admin account
PUT http://localhost:8080/cities/edit/2/approve
Authorization: Basic MzkzODc6bjBVMnlzTTk=

### Deletes creates cities request. Requries admin account
PUT http://localhost:8080/cities/edit/2/decline
Authorization: Basic MzkzODc6bjBVMnlzTTk=

### Gets a list of requests for specified user
GET http://localhost:8080/cities/edit
Authorization: Basic MzkzODc6bjBVMnlzTTk=

### Gets a list of all opened requests
GET http://localhost:8080/cities/edit/opened
Authorization: Basic MzkzODc6bjBVMnlzTTk=